/**
 * __PROJECT_NAME__ — generated by @yiong/mcp-chinese-rag-toolkit
 *                    create-mcp-rag on __SCAFFOLD_DATE__
 *
 * Minimal MCP server exposing a `search_docs` tool that runs BM25 (jieba
 * FTS5) over `data/index.db` — built once via `pnpm build-index`. Switch
 * to the real bge-large-zh-v1.5 embedder + hybrid + rerank pipeline by
 * editing `scripts/build-index.ts` (see toolkit README §Hybrid Search).
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createMcpServer, defineTool, openIndex } from '@yiong/mcp-chinese-rag-toolkit';
import { z } from 'zod';

const here = path.dirname(fileURLToPath(import.meta.url));
const indexPath = path.resolve(here, '..', 'data', 'index.db');

const index = openIndex(indexPath, { readonly: true });

const searchDocs = defineTool({
  name: 'search_docs',
  description: 'Search local docs by BM25 (Chinese-tokenized via jieba). Returns top chunks.',
  whenToUse: 'Use when the user asks a factual question that should be answered from local docs.',
  inputSchema: z.object({
    query: z.string().min(1).max(200),
    topK: z.number().int().min(1).max(20).default(5),
  }),
  handler: (args) => {
    const hits = index.ftsSearch(args.query, { topK: args.topK });
    return {
      content: [{ type: 'text', text: JSON.stringify(hits, null, 2) }],
      structuredContent: {
        hits,
        confidence: hits.length > 0 ? 'high' : 'low',
      },
    };
  },
});

const handle = createMcpServer({
  name: '__PROJECT_NAME__',
  version: '0.1.0',
  transport: 'stdio',
  tools: [searchDocs],
});

await handle.start();
