/**
 * Public package identifier. Retained as a literal-typed sanity constant so
 * downstream consumers can verify ESM / CJS / TS resolution end-to-end.
 */
export const TOOLKIT_NAME = 'mcp-chinese-rag-toolkit' as const;

export type ToolkitName = typeof TOOLKIT_NAME;

export type {
  AnswerCorrectnessResult,
  AnswerCorrectnessStatement,
  AnswerRelevanceInput,
  AnswerRelevanceResult,
  ClaimVerdict,
  ContextPrecisionResult,
  ContextRecallResult,
  CorrectnessLabel,
  EvalErrorCode,
  EvalExpected,
  EvalQuery,
  EvalQueryResult,
  EvalRunnerOptions,
  EvalSearchFn,
  EvalSearchResult,
  EvalSet,
  EvalSummary,
  FaithfulnessResult,
  NdcgResult,
  WriteArtifactsOptions,
} from './eval/index.js';
export {
  answerCorrectness,
  answerRelevance,
  assertContentPopulated,
  contextPrecision,
  contextRecall,
  cosineSimilarity,
  DEFAULT_EVAL_TOP_K,
  DEFAULT_HIT_RATE_MIN,
  DEFAULT_RESULTS_DIR,
  EVAL_ERROR_CODES,
  EvalFrameworkError,
  emitGitHubActionsAnnotation,
  evalError,
  faithfulness,
  loadEvalSet,
  ndcg,
  passesGate,
  renderMarkdownReport,
  resolveHitRateMin,
  runEval,
  scoreQuery,
  writeArtifacts,
} from './eval/index.js';
export type { ToolHandler } from './middleware/with-lru-cache.js';
export {
  canonicalize,
  computeCacheKey,
  injectCacheMeta,
  NON_CACHEABLE_ARGS,
  shouldSkipWrite,
  withLruCache,
} from './middleware/with-lru-cache.js';
export type {
  CacheOptions,
  CacheStatus,
  CaptionCache,
  CaptionCacheEntry,
  CaptionCacheLookup,
  CaptionCacheOptions,
  Chunk,
  ChunkOptions,
  ChunkRow,
  ContextualRetrievalOptions,
  Embedder,
  EmbedderOptions,
  FtsHit,
  FusedRow,
  HarnessResult,
  HybridHit,
  HybridSearchDeps,
  HybridSearchFn,
  HybridSearchOptions,
  IndexHandle,
  IndexingPlugin,
  IndexingPluginContext,
  IndexStats,
  LatencyHarnessOptions,
  LatencySnapshot,
  LlmProvider,
  ManifestEntry,
  ModelManifest,
  OpenIndexOptions,
  PageCaptionOptions,
  ParsePdfResult,
  PdfPage,
  RankedDocument,
  RankedRow,
  RerankedHit,
  Reranker,
  RerankerDeps,
  RerankerOptions,
  RerankFn,
  RerankOptions,
  RrfOptions,
  SchemaOptions,
  SearchOptions,
  VecHit,
  VisionCaptionOptions,
  VisionProvider,
  WithLruCacheDeps,
} from './rag/index.js';
export {
  BGE_LARGE_ZH_V1_5_MANIFEST,
  BGE_RERANKER_V2_M3_MANIFEST,
  buildSchema,
  chunk,
  chunkPdfPages,
  configureTransformersEnv,
  createHybridSearch,
  createReranker,
  DEFAULT_PREFIX_LENGTH,
  DEFAULT_VISION_PROMPT,
  encodePng,
  ensureCanvasAvailable,
  generateChunkContext,
  JIEBA_VERSION,
  loadEmbedder,
  loadReranker,
  ModelFileMissingError,
  ModelHashMismatchError,
  OptionalDependencyMissingError,
  openCaptionCache,
  openIndex,
  parsePdf,
  percentile,
  renderChunkContextPrompt,
  resolveCacheDir,
  resolveDefaultCaptionCacheDir,
  rrfFuse,
  runStdioLatencyHarness,
  sha256Hex,
  stitchPrefixedChunk,
  tokenize,
  VisionCaptionFailedError,
  verifyModelFiles,
  withPageCaption,
  withVisionCaption,
  writeEmbedderMeta,
  writeRerankerMeta,
  writeTokenizerMeta,
} from './rag/index.js';
export type {
  McpServerCacheConfig,
  McpServerConfig,
  McpServerHandle,
  McpToolDefinition,
} from './server/create-mcp-server.js';
export { createMcpServer } from './server/create-mcp-server.js';
export type {
  Citation,
  ConfidenceLevel,
  StructuredErrorPayload,
} from './server/errors.js';
export * as errors from './server/errors.js';
export type { ToolHookContext, ToolHooks } from './server/instrumentation-hooks.js';
export { withHooks } from './server/instrumentation-hooks.js';
export type {
  ResourceDefinition,
  ResourceDefinitionInput,
  ResourceListEntry,
  ResourceReadResult,
} from './server/resource-provider.js';
export { defineResources } from './server/resource-provider.js';
export type { ToolDefinitionInput, ToolExample } from './server/tool-builder.js';
export { defineTool } from './server/tool-builder.js';
